# Generated by Django 5.1.1 on 2025-11-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_achievement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='achievement_claims',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='achievement_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
