# Generated by Django 5.1.1 on 2025-01-31 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='bronze', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BonusMalusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='bonus_malus_images/')),
                ('rarity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.cardrarity')),
            ],
        ),
        migrations.CreateModel(
            name='CoachCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('BERGAMO', 'Bergamo'), ('VIRTUS', 'Virtus'), ('4MORI', '4 Mori'), ('LAKECITY', 'Lake City'), ('TOSCANI', 'Toscani'), ('VIOLA', 'Viola'), ('GRIFONI', 'Grifoni'), ('VENETI', 'Veneti'), ('LOMBARDIA', 'Lombardia'), ('ZEBRE', 'Zebre'), ('AQUILE', 'Aquile'), ('SALENTO', 'Salento'), ('DIAVOLI', 'Diavoli'), ('BRIANZA', 'Brianza'), ('PARTENOPI', 'Partenopi'), ('PARMIGIANI', 'Parmigiani'), ('LUPI', 'Lupi'), ('GRANATA', 'Granata'), ('FRIULANI', 'Friulani'), ('LEONI', 'Leoni')], default='BERGAMO', max_length=20)),
                ('attack_bonus', models.FloatField()),
                ('defense_bonus', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='coach_images/')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_cards', to='cards.cardrarity')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('BERGAMO', 'Bergamo'), ('VIRTUS', 'Virtus'), ('4MORI', '4 Mori'), ('LAKECITY', 'Lake City'), ('TOSCANI', 'Toscani'), ('VIOLA', 'Viola'), ('GRIFONI', 'Grifoni'), ('VENETI', 'Veneti'), ('LOMBARDIA', 'Lombardia'), ('ZEBRE', 'Zebre'), ('AQUILE', 'Aquile'), ('SALENTO', 'Salento'), ('DIAVOLI', 'Diavoli'), ('BRIANZA', 'Brianza'), ('PARTENOPI', 'Partenopi'), ('PARMIGIANI', 'Parmigiani'), ('LUPI', 'Lupi'), ('GRANATA', 'Granata'), ('FRIULANI', 'Friulani'), ('LEONI', 'Leoni')], default='BERGAMO', max_length=20)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('abilities', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='player_images/')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_cards', to='cards.cardrarity')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_malus_cards', models.ManyToManyField(blank=True, related_name='owned_by_users', to='cards.bonusmaluscard')),
                ('coach_cards', models.ManyToManyField(blank=True, related_name='owned_by_users', to='cards.coachcard')),
                ('player_cards', models.ManyToManyField(blank=True, related_name='owned_by_users', to='cards.playercard')),
            ],
        ),
    ]
