# Generated by Django 5.1.1 on 2025-01-31 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdeck',
            name='bonus_malus_cards',
            field=models.ManyToManyField(blank=True, related_name='decks', to='cards.bonusmaluscard'),
        ),
        migrations.AddField(
            model_name='userdeck',
            name='coach_cards',
            field=models.ManyToManyField(blank=True, related_name='decks', to='cards.coachcard'),
        ),
        migrations.AddField(
            model_name='userdeck',
            name='player_cards',
            field=models.ManyToManyField(blank=True, related_name='decks', to='cards.playercard'),
        ),
        migrations.AddField(
            model_name='userdeck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
