# Generated by Django 5.1.1 on 2025-11-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_add_season_to_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalkeeperCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('BERGAMO', 'Bergamo'), ('VIRTUS', 'Virtus'), ('4MORI', '4 Mori'), ('LAKECITY', 'Lake City'), ('TOSCANI', 'Toscani'), ('VIOLA', 'Viola'), ('GRIFONI', 'Grifoni'), ('VENETI', 'Veneti'), ('LOMBARDIA', 'Lombardia'), ('ZEBRE', 'Zebre'), ('AQUILE', 'Aquile'), ('SALENTO', 'Salento'), ('DIAVOLI', 'Diavoli'), ('BRIANZA', 'Brianza'), ('PARTENOPI', 'Partenopi'), ('PARMIGIANI', 'Parmigiani'), ('LUPI', 'Lupi'), ('GRANATA', 'Granata'), ('FRIULANI', 'Friulani'), ('LEONI', 'Leoni')], default='BERGAMO', max_length=20)),
                ('season', models.CharField(default='24/25.1', max_length=20)),
                ('save', models.IntegerField()),
                ('abilities', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='goalkeeper_images/')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalkeeper_cards', to='cards.cardrarity')),
            ],
        ),
        migrations.AddField(
            model_name='usercollection',
            name='goalkeeper_cards',
            field=models.ManyToManyField(blank=True, related_name='owned_by_users', to='cards.goalkeepercard'),
        ),
        migrations.AddField(
            model_name='userdeck',
            name='goalkeeper_cards',
            field=models.ManyToManyField(blank=True, related_name='decks', to='cards.goalkeepercard'),
        ),
    ]
