# Generated by Django 5.1.1 on 2025-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_save_goalkeepercard_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalkeepercard',
            name='saves',
            field=models.IntegerField(verbose_name='saves (%)'),
        ),
    ]
