"""
Django settings for db_carte project.

Generated by 'django-admin startproject' using Django 5.1.1.
"""

from pathlib import Path
import os

# --------------------------------------------------------------------------------
# Base Directory
# --------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------------
# Security Settings
# --------------------------------------------------------------------------------
SECRET_KEY = 'django-insecure-xf#vh80)ibp(yvu*dtd6pu*@_vf-gcgnr6^$plzx*3+)-wwynz'

DEBUG = True  # WARNING: Disable this in production!

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '46ee1e42605c.ngrok-free.app',  # Ngrok URL
]

CSRF_TRUSTED_ORIGINS = [
    'https://127.0.0.1',
    'https://localhost',
    'https://46ee1e42605c.ngrok-free.app',  # Ngrok URL
]

# --------------------------------------------------------------------------------
# Installed Applications
# --------------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',  # Deve comparire solo una volta
    'users',
    'cards',
    'quiz',
]

# --------------------------------------------------------------------------------
# Middleware
# --------------------------------------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------------------------------------
# URLs and WSGI
# --------------------------------------------------------------------------------
ROOT_URLCONF = 'db_carte.urls'

WSGI_APPLICATION = 'db_carte.wsgi.application'

# --------------------------------------------------------------------------------
# Database Configuration
# --------------------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --------------------------------------------------------------------------------
# Authentication
# --------------------------------------------------------------------------------
AUTH_USER_MODEL = 'users.CustomUser'

# Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------------------------------------
# Internationalization
# --------------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# --------------------------------------------------------------------------------
# Static and Media Files
# --------------------------------------------------------------------------------
STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --------------------------------------------------------------------------------
# Django REST Framework Configuration
# --------------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# --------------------------------------------------------------------------------
# CORS Configuration
# --------------------------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True  # WARNING: Use specific origins in production!

# --------------------------------------------------------------------------------
# Default Auto Field
# --------------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------------------------------------------------------------------
# Templates Configuration
# --------------------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Directory dei template
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Necessario per l'admin
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
