# Generated by Django 5.1.1 on 2025-10-29 08:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('cards_per_pack', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('price', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PackPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('cards_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='packs.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PackPurchaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_cards', to='packs.packpurchase')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardrarity')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PackRarityWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Percentage weight for this rarity within the pack.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rarity_weights', to='packs.pack')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_weights', to='cards.cardrarity')),
            ],
            options={
                'ordering': ('pack', 'rarity__name'),
                'unique_together': {('pack', 'rarity')},
            },
        ),
    ]
